### ISSUE TITLE
RLOS output should be tied to observer point in some way

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-geoprocessing-toolbox#50]
The features created should be able to identify what observer they are a part of

**Comment by mfunk** [comment]
Should investigate doing Viewshed2 twice, once with the FREQUENCY option and then again with the OBSERVERS option and relate/union/intersect the two. That way we can get both sets of info.

```
Analysis type (optional)
Choose which type of visibility analysis you wish to perform, either determining how visible each cell
 is to the observers, or identifying for each surface location which observers are visible.

* FREQUENCY—The output records the number of times that each cell location in the input surface
 raster can be seen by the input observation locations (as points or as vertices for polyline observer
 features). This is the default.
 
* OBSERVERS — The output identifies exactly which observer points are visible from each raster
 surface location. The allowed maximum number of input observers is 32 with this analysis type.
 
```

**Comment by adgiles** [comment]
Addressed in PR #216 please can somebody verify once merged.

This may require documentation changes

**Comment by NatalieCampos** [comment]
@adgiles I tried this on github on **two** different machines.  The tool fails to execute and gives the error below.  Something to do with the video card.  I also tried updating my video card driver for each machine, but I still get the error.

![image](https://cloud.githubusercontent.com/assets/5116835/26211815/4a13d028-3ba8-11e7-9277-679500044ef4.png)

**Comment by adgiles** [comment]
Going to revert the changes due to the limitation of the Viewshed2 tool:

Currently, this tool only supports NVIDIA graphics cards with CUDA compute capability 2.0 or OpenCL 1.2 and is dependent on your system having an appropriate card installed. To ensure proper tool execution, see the NVIDIA driver update pageNVIDIA driver downloads for the latest available driver.

**Comment by adgiles** [comment]
@NatalieCampos can you verify the tool is back to how it was originally working

**Comment by NatalieCampos** [comment]
Tool seems back to original working condition.  This issue/enhancement will not be closed but assignments will be removed.

**Comment by topowright** [comment]
The creation of this issue really does not explain what was needed. Running this in ArcMap it does not create an output for observer point, but out of the box the gp tool does this for ArcGIS Pro. I feel like if we added and output for observer point that would be the first step to understanding what observer is tied to what RLOS; however, that would only be done visually. Does anyone think we should be saving each RLOS as its on feature class? @dfoll @ACueva
